services:
  workspace:
    container_name: rag_mcp_devcon_workspace
    image: mcr.microsoft.com/devcontainers/base:bullseye
    command: sleep infinity
    volumes:
      # Workspace Cache
      - ..:${containerWorkspaceFolder}:cached
      # Mount Cursor MCP settings from host
      - ~/.cursor:/home/vscode/.cursor:cached
      - ~/.config/cursor:/home/vscode/.config/cursor:cached
      # Mount SSH keys for git operations
      - ~/.ssh:/home/vscode/.ssh:ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      # Ensure MCP settings are available
      - CURSOR_USER_CONFIG_DIR=/home/vscode/.config/cursor
      - CURSOR_GLOBAL_CONFIG_DIR=/home/vscode/.cursor